a=int(input("Nolga teng bo'lmagan birinchi sonni kiriting: "))
b=int(input("Nolga teng bo'lmagan ikkinchi sonni kiriting:: "))
print('S=', a+b)
print('P=', a*b)
print('K=', abs(a))
print('K1=', abs(b))