x1=int(input("Berilgan birinchi nuqtaning birinchi kordinatasini kiriting: "))
y1=int(input("Berilgan birinchi nuqtaning ikkinchi kordinatasini kiriting: "))
x2=int(input("Berilgan ikkinchi nuqtaning birinchi kordinatasini kiriting: "))
y2=int(input("Berilgan ikkinchi nuqtaning birinchi kordinatasini kiriting: "))
print("Berilgan nuqtalar orasidagi masofa= ", ((x2-x1)**2+(y2-y1)**2)**(1/2))