A=int(input("Sonni kiriting: "))
print("A soning kvadrati=", A**2)
print("A soning uchunchii darajasi=", A**3)
print("A soning beshinchi darajasi=", A**5)
print("A soning o'ninchi darajasi=", A**10)
print("A soning o'nbeshinchi darajasi=", A**15)
